config/routes.rb
Rails.application.routes.draw do
  resources :rooms
  root to: 'home#index'
  
  devise_for :users
end

app/models/application_record.rb
# main database record class that sits between app and Rails
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
# Rooms that can be rented.
class Room < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :capacity, presence: true, numericality: { greater_than: 1 }
  validates :rate, presence: true, numericality: { greater_than: 0.00 }
  validates :notes, presence: true
end

app/models/room_rental.rb
# rental of a room
class RoomRental < ApplicationRecord
  validates :room_id, presence: true
  validates :user_id, presence: true
  validates :rented_date, presence: true
  validates :start_time, presence: true
  validates :end_time, presence: true
  validates :notes, presence: true

  belongs_to :user
  belongs_to :room
end

app/models/user.rb
# model to authenitcate for the application
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
# main controller that sits between app and the Rails stack
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# renders the homnepage
class HomeController < ApplicationController
  def index; end
end

app/controllers/room_rentals_controller.rb
class RoomRentalsController < ApplicationController
  before_action :set_room_rental, only: [:show, :edit, :update, :destroy]

  # GET /room_rentals
  # GET /room_rentals.json
  def index
    @room_rentals = RoomRental.all
  end

  # GET /room_rentals/1
  # GET /room_rentals/1.json
  def show
  end

  # GET /room_rentals/new
  def new
    @room_rental = RoomRental.new
  end

  # GET /room_rentals/1/edit
  def edit
  end

  # POST /room_rentals
  # POST /room_rentals.json
  def create
    @room_rental = RoomRental.new(room_rental_params)

    respond_to do |format|
      if @room_rental.save
        format.html { redirect_to @room_rental, notice: 'Room rental was successfully created.' }
        format.json { render :show, status: :created, location: @room_rental }
      else
        format.html { render :new }
        format.json { render json: @room_rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /room_rentals/1
  # PATCH/PUT /room_rentals/1.json
  def update
    respond_to do |format|
      if @room_rental.update(room_rental_params)
        format.html { redirect_to @room_rental, notice: 'Room rental was successfully updated.' }
        format.json { render :show, status: :ok, location: @room_rental }
      else
        format.html { render :edit }
        format.json { render json: @room_rental.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /room_rentals/1
  # DELETE /room_rentals/1.json
  def destroy
    @room_rental.destroy
    respond_to do |format|
      format.html { redirect_to room_rentals_url, notice: 'Room rental was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room_rental
      @room_rental = RoomRental.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_rental_params
      params.require(:room_rental).permit(:user_id, :room_id, :date, :start_time, :end_time, :note, :paid_amount)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :capacity, :rate, :discount, :note)
    end
end

app/helpers/application_helper.rb
# view helper methods for the application layout
module ApplicationHelper
end

app/helpers/room_rentals_helper.rb
module RoomRentalsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/home/index.html.erb
<ul>
    <li><%= link_to "Room Rentals", room_rentals_path %></li>
</ul>
<h1>Welcome to Event Center Calendar!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventCenterCallendar</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/room_rentals/_form.html.erb
<%= form_with(model: room_rental, local: true) do |form| %>
  <% if room_rental.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room_rental.errors.count, "error") %> prohibited this room_rental from being saved:</h2>

      <ul>
      <% room_rental.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, id: :room_rental_user_id %>
  </div>

  <div class="field">
    <%= form.label :room_id %>
    <%= form.number_field :room_id, id: :room_rental_room_id %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.datetime_select :date, id: :room_rental_date %>
  </div>

  <div class="field">
    <%= form.label :start_time %>
    <%= form.time_select :start_time, id: :room_rental_start_time %>
  </div>

  <div class="field">
    <%= form.label :end_time %>
    <%= form.time_select :end_time, id: :room_rental_end_time %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note, id: :room_rental_note %>
  </div>

  <div class="field">
    <%= form.label :paid_amount %>
    <%= form.text_field :paid_amount, id: :room_rental_paid_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/room_rentals/edit.html.erb
<h1>Editing Room Rental</h1>

<%= render 'form', room_rental: @room_rental %>

<%= link_to 'Show', @room_rental %> |
<%= link_to 'Back', room_rentals_path %>

app/views/room_rentals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Room Rentals</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Room</th>
      <th>Date</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Note</th>
      <th>Paid amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @room_rentals.each do |room_rental| %>
      <tr>
        <td><%= room_rental.user_id %></td>
        <td><%= room_rental.room_id %></td>
        <td><%= room_rental.date %></td>
        <td><%= room_rental.start_time %></td>
        <td><%= room_rental.end_time %></td>
        <td><%= room_rental.note %></td>
        <td><%= room_rental.paid_amount %></td>
        <td><%= link_to 'Show', room_rental %></td>
        <td><%= link_to 'Edit', edit_room_rental_path(room_rental) %></td>
        <td><%= link_to 'Destroy', room_rental, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room Rental', new_room_rental_path %>

app/views/room_rentals/new.html.erb
<h1>New Room Rental</h1>

<%= render 'form', room_rental: @room_rental %>

<%= link_to 'Back', room_rentals_path %>

app/views/room_rentals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @room_rental.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @room_rental.room_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @room_rental.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @room_rental.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @room_rental.end_time %>
</p>

<p>
  <strong>Note:</strong>
  <%= @room_rental.note %>
</p>

<p>
  <strong>Paid amount:</strong>
  <%= @room_rental.paid_amount %>
</p>

<%= link_to 'Edit', edit_room_rental_path(@room_rental) %> |
<%= link_to 'Back', room_rentals_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :room_name %>
  </div>

  <div class="field">
    <%= form.label :capacity %>
    <%= form.number_field :capacity, id: :room_capacity %>
  </div>

  <div class="field">
    <%= form.label :rate %>
    <%= form.text_field :rate, id: :room_rate %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount, id: :room_discount %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note, id: :room_note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Capacity</th>
      <th>Rate</th>
      <th>Discount</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.capacity %></td>
        <td><%= room.rate %></td>
        <td><%= room.discount %></td>
        <td><%= room.note %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @room.capacity %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @room.rate %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @room.discount %>
</p>

<p>
  <strong>Note:</strong>
  <%= @room.note %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>